language: node_js
node_js:
  - 0.10
before_install:
  - npm install mongoose connect-mongo lwip socket.io mubsub
services:
  - mongodb
branches:
  only:
    - master
after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage